### ISSUE TITLE
Vala Programming Language/Projects not shown in List

### ISSUE THREAD

**Issue by bigfatbird** [24pullrequests/contribulator#1309]
On the contribulator website Vala Projects are not tracked currently

**Comment by andrew** [comment]
Thanks for reporting, do you have an example vala repo I can use for testing?

**Comment by bigfatbird** [comment]
I just yesterday submitted some repos from elementary OS

For example:

* https://github.com/elementary/files
* github.com/elementary/appcenter

**Comment by bigfatbird** [comment]
I'm wondering if there is a way to synchronize languages available on 24pr, with languages in the contribulator 🤔

**Comment by andrew** [comment]
I suspect the problem is that contribulator isn’t downloading all the details from GitHub, either due to rate limits or invalid api keys

**Comment by andrew** [comment]
https://contribulator.24pullrequests.com/?language=Vala

**Comment by bigfatbird** [comment]
Those are showing up now.


To understand the problem: Rhe rest will be synced „someday“ if GitHub allows it, or do you need to do this manually?

**Comment by andrew** [comment]
Contribulator is mostly manual at the moment, although any projects added to 24pullrequests.com should show up there automatically

**Comment by bigfatbird** [comment]
Okay cool. Let's see when the rest will get synced. Wish I could help, but I'm so not a rubyist
