### ISSUE TITLE
[BUG] Unable log in

### ISSUE THREAD

**Issue by mbiesiad** [24pullrequests/contribulator#1312]
Go to:
https://contribulator.24pullrequests.com/

Click: Log in
See the message:

> Project not found
> auth/github was not found, would you like to add it?

Best wishes,

**Comment by andrew** [comment]
The functionality of this repo has been merged into the main 24pullrequests repository, this repo and it's issue tracker will no longer be used and the contributlator website is being shut  down, for more details see: https://github.com/24pullrequests/24pullrequests/discussions/3514
