### ISSUE TITLE
[BUG] Filter by language disappear

### ISSUE THREAD

**Issue by mbiesiad** [24pullrequests/contribulator#1313]
Type: https://contribulator.24pullrequests.com/search?q=TypeScript
See:
![image](https://user-images.githubusercontent.com/18367606/145653045-cb741a82-ead7-4afe-87fc-fe639e560dd1.png)

Change the browser window (make smaller), result:
![image](https://user-images.githubusercontent.com/18367606/145653090-9cac7ade-a478-45d3-8aeb-56a6f4225de2.png)

"Filter by language" disappeared.

Best wishes,

**Comment by andrew** [comment]
The functionality of this repo has been merged into the main 24pullrequests repository, this repo and it's issue tracker will no longer be used and the contributlator website is being shut  down, for more details see: https://github.com/24pullrequests/24pullrequests/discussions/3514
