### ISSUE TITLE
[BUG] Search field and Log in button disappear

### ISSUE THREAD

**Issue by mbiesiad** [24pullrequests/contribulator#1314]
Similar like with issue #1313 

Go to: https://contribulator.24pullrequests.com/
Change browser window (make smaller).
See that Search field and Search/Log in button disapeared.

Best wishes,

**Comment by andrew** [comment]
The functionality of this repo has been merged into the main 24pullrequests repository, this repo and it's issue tracker will no longer be used and the contributlator website is being shut  down, for more details see: https://github.com/24pullrequests/24pullrequests/discussions/3514
