### ISSUE TITLE
Incorrect counts on projects

### ISSUE THREAD

**Issue by davejlong** [24pullrequests/contribulator#417]
Contribulator shows 812 Open Issues and 30 Commits in the last 6 months on every project.

**Comment by davejlong** [comment]
The Calculator doesn't have any filter to the project https://github.com/andrew/contribulator/blob/master/app/models/score_calculator.rb#L90

**Comment by andrew** [comment]
@davejlong good spot, that's definitely the bug!

**Comment by andrew** [comment]
@davejlong I've fixed and deployed that and kicked off a task to update the score on every project 🚢

**Comment by davejlong** [comment]
Not sure how long the job takes, but now it looks like all projects are showing 10 issues and 30 commits. At least kittoframework/kitto and rails/rails are...

**Comment by andrew** [comment]
Looks like the task failed, I suspect it ran out of memory trying to load all the rails issues into ram!

**Comment by hanmd82** [comment]
@andrew does this still need to be looked into? :)
