### ISSUE TITLE
URLs for adding projects

### ISSUE THREAD

**Issue by ghost** [24pullrequests/contribulator#444]
When adding a project from 24pullrequests for scoring on contribulator, URLs don't seem to work.

What format should they be in?
* username/repo
* github.com/username/repo
* https://github.com/username/repo

And should there be any hints when adding a project?

* hints or code to handle the above conditions?

Expectation: add `Thetoxicarcade/congredi`

Result: error page (see log for details)

**Comment by andrew** [comment]
I have a feeling it's `https://github.com/username/repo` but it makes sense that all three should work, if they don't it's a bug
