### ISSUE TITLE
Add index to Projects db table

### ISSUE THREAD

**Issue by andrew** [24pullrequests/contribulator#53]
We can speed up the rendering of `ProjectsController#index` and `ProjectsController#show` by adding a couple of indexes to the Projects table.

Check out the existing queries made by the controller with `explain` in the psql console and then add indexes to improve them as a migration.

Some potential fields we're using:
- score
- last_scored
- main_language (case-insensitive)
- name
- owner

**Comment by hanmd82** [comment]
@andrew this issue can be closed as it was resolved in https://github.com/24pullrequests/contribulator/pull/235 :)
