### ISSUE TITLE
Login button takes you to Github?

### ISSUE THREAD

**Issue by oluoluoxenfree** [24pullrequests/contribulator#57]
I'm not sure what logging in is supposed to do in any case, errant button?

**Comment by wadtech** [comment]
Hi @oluoluoxenfree,

The current behaviour (should be) an oauth flow to github to allow adding projects, it also allows the user to see which of their repositories have been added already.

I don't think we need to have a user login at all currently- all it does is give permission to project#new and a very sparse user page that lists their projects already added to contribulator.

@andrew might have his own opinions on this so feel free to chat about it at http://gitter.im/andrew/contribulator or submit a pull request with some ideas.

Thanks :+1:

**Comment by andrew** [comment]
The main reason I added it was because we need a certain number of valid oauth tokens to be able to download repo information from the github api, which we have now, so I don't see why the log in requirement can't removed now.
