### ISSUE TITLE
Bitbucket integration

### ISSUE THREAD

**Issue by wadtech** [24pullrequests/contribulator#59]
Bitbucket has a good API so there's no reason to only support Github.

I'm not sure what impact that would have on the score calculator so it'd need making sure that it's possible for alternative providers without losing any (or too much) of the variables that make up the score.

**Comment by andrew** [comment]
:+1: yeah, as long as we can check for the presence of files via the api then it should be good

**Comment by wadtech** [comment]
Looks like that API exists: https://confluence.atlassian.com/display/BITBUCKET/src+Resources

All of the gems are unmaintained or out of date so I'll see whether they still work OK or whether a bit more work would be required (roll our own or fork or something)

**Comment by andrew** [comment]
@wadtech this one seems like the best bet: http://libraries.io/rubygems/bitbucket_rest_api

**Comment by wadtech** [comment]
That was the one I was leaning towards. Neato.
