### ISSUE TITLE
Automatically populate the list of languages using Linguist

### ISSUE THREAD

**Issue by pchaigno** [24pullrequests/contribulator#71]
GitHub uses Linguist (Ruby gem name is `github-linguist`) to identify the languages of repositories. Contribulator could use it to retrieve the list of supported languages.
There are a good number of supported languages so it would require a few changes to the web UI.

Would you consider this?

**Comment by wadtech** [comment]
Hi @pchaigno 

Thanks for your suggestion. Seems sensible to me.

Would you be interested in opening a PR for this? I'm happy to help where I can.

**Comment by andrew** [comment]
I've actually made a gem that would be useful for this: https://github.com/librariesio/languages

`github-linguist` has some dependencies that are difficult to install on heroku so I extracted just the language sections out into a separate gem to make it easy to use, @pchaigno you could use that to get all the languages:

```ruby
Languages::Language.all #=> [#<Languages::Language name=ActionScript color=#e3491a>, ..]
```

**Comment by wadtech** [comment]
:+1:
