### ISSUE TITLE
Contribulator's "Contributing present"

### ISSUE THREAD

**Issue by hugovk** [24pullrequests/contribulator#714]
https://contribulator.24pullrequests.com/python-pillow/Pillow says "Contributing present: false" when it does have a CONTRIBUTING.md, it's in the .github directory, not the root.

https://github.com/python-pillow/Pillow/blob/master/.github/CONTRIBUTING.md

https://help.github.com/articles/setting-guidelines-for-repository-contributors/ says:

> To help your project contributors do good work, you can add a file with contribution guidelines to your project repository's root, `docs`, or `.github` folder.

**Comment by andrew** [comment]
Ah yeah that's a bug then, good spot!
