### ISSUE TITLE
Can't add a project, app breaks

### ISSUE THREAD

**Issue by vadi2** [24pullrequests/contribulator#715]
Going to https://contribulator.herokuapp.com/projects/confirm?url=mudlet%2Fmudlet and hitting Add makes the app crash.

**Comment by andrew** [comment]
Thanks for reporting, I'll check out what's going on there

**Comment by StevenCopeland** [comment]
Same for me.... Can't add anything.

**Comment by andrew** [comment]
I think there's a bug in production with talking to the GitHub app, will continue to investigate tomorrow.

**Comment by elv1s42** [comment]
Hi All,

I am having the same issue when trying to add this project: 
https://github.com/jdi-testing/jdi-light-csharp/

Thank you

**Comment by elv1s42** [comment]
@andrew , can you please take a look at the issue with https://github.com/jdi-testing/jdi-light-csharp/ ?
I've tried different browsers, but still no luck.

**Comment by elv1s42** [comment]
I've added a new related [issue](https://github.com/24pullrequests/contribulator/issues/853)
